### ISSUE TITLE
There's not way to specify the order that routes are resolved

### ISSUE THREAD

**Issue by moefinley** [ng-apimock/core#10]
I have two API endpoints
`v1/workflows/`
`v1/workflows/tabs/`

The mocks for these two endpoints only work when the files are named to be parsed in a certain order. For example:
`workflows.mock.json`
`workflows-tabs.mock.json`
Doesn't work because workflows.mock.json is resolved before workflows-tabs.mock.json. However:
`a-workflows-tabs.mock.json`
`workflows.mock.json`
Works correctly because the routes are resolved the other way around.

I couldn't find anything in the documentation that explained another way to do this other than file naming. This seems unlikely. Am I missing something?

**Comment by mdasberg** [comment]
hi @moefinley you can use a regex for your url in such a way that you can specify the first url
(v1/workflows) to work only when there is nothing behind it.

So for /v1/workflows/
```json
{
    "request": {
         "url": "v1/workflows/$",
         "method": "GET"
     }
}
```

and for /v1/workflows/tabs/
```json
{
    "request": {
         "url": "v1/workflows/tabs/$",
         "method": "GET"
     }
}
```

So the order is not necessary.

**Comment by mdasberg** [comment]
@moefinley thanks for pointing that out to me, I will update the documentation
