### ISSUE TITLE
Body matching with regex not working when migrating from old ng-apimock

### ISSUE THREAD

**Issue by ganeshps17** [ng-apimock/core#1039]
The below mock used to work with the old ng-apimock. With the new version this is not working.
https://www.npmjs.com/package/ng-apimock#howto-write-mocks

Actual request body content:
![image](https://user-images.githubusercontent.com/87961350/225016154-18d8ea63-49ce-4308-9db8-6a8a946c50e0.png)

Mock json:- 
`{
  "name": "post-test-mock",
  "isArray": false,
  "responses": {
    "default": {
      "default": true,
      "delay": 1000,
      "data": {
        "mock": "mock"
      }
    }
  },
  "request": {
    "url": "/mock/url/api.php",
    "body": "(.*)page=0&page_size=25(.*)",
    "method": "POST"
  }
}`

Also the migration script is not updating the body in a request
https://github.com/ng-apimock/core/blob/master/MIGRATION.md#convert-your-mocks-to-the-new-json-format

**Comment by ganeshps17** [comment]
@mdasberg , Is anything wrong with the mock I've provided or the new version doesn't support this

**Comment by mdasberg** [comment]
Hi @ganeshps17, what is the url you are hitting the api with?

**Comment by mdasberg** [comment]
@ganeshps17 matching the request body currently only works for json payloads.

So if your payload would be something like this:

```json
{
  "nested": {
    "number": 123,
    "identifier": "abcd"
  }
}
```

you would be able to match exactly with a mock.json like this:
```json
{
  "name": "advanced-nested",
  "request": {
    "url": "some/api",
    "method": "POST",
    "headers": {
      "Content-Type": "application/json",
      "Cache-Control": "no-cache"
    },
    "body": {
      "nested": {
        "number": "\\d+",
        "identifier": "^[a-zA-Z]{4}$"
      }
    }
  },
  "responses": {
    "three": {},
    "four": {}
  }
}
```

**Comment by mdasberg** [comment]
@ganeshps17 is it an option to use a json payload?

**Comment by ganeshps17** [comment]
> @ganeshps17 is it an option to use a json payload?

No, the api that i'm using mock for doesn't support json payload. It accepts url-encoded payload on body.
![image](https://user-images.githubusercontent.com/87961350/226825248-11b1e8b1-9fe4-4a77-90ef-28b0e7513d9e.png)

Is there any plans to support non-json payloads in newer version of ng-api-mock core like in older version
https://www.npmjs.com/package/ng-apimock

**Comment by AlexMabry** [comment]
I made an attempt to add support for this request. Please consider this pull request: https://github.com/ng-apimock/core/pull/1056

**Comment by mdasberg** [comment]
Hi @AlexMabry, I will have a look at it. Thanks for creating a pr

**Comment by mdasberg** [comment]
@AlexMabry @ganeshps17 The pr has been merged. [v3.10.0](https://github.com/ng-apimock/core/releases/tag/v3.10.0) has been released

@AlexMabry once again, thank you for your contribution

**Comment by AlexMabry** [comment]
@mdasberg Thank you for writing and maintaining this project.
