### ISSUE TITLE
Mock response variable not replaced when defined in "file"

### ISSUE THREAD

**Issue by DHFW** [ng-apimock/core#1044]
When a mock response contains a variable like `"%%today%%"` in a scenario when using the "data" property, this works fine.
But when the same mock response that has a variable is defined via the "file" property, the variable is not replaced.

I would be nice to have this functionality also work when using files. Using version 3.5.0.

**Comment by mdasberg** [comment]
@DHFW this is actually possible. But you need to specify the content-type as 
```
application/json
``` 

like this 

```json
{
  "name": "my-mock",
  "isArray": false,
  "request": {
    "url": "/some/url",
    "method": "GET"
  },
  "responses": {
    "dummy": {
      "data": [
        {
          "description": "%%dummy-description%%"
        }
      ]
    },
    "dummy-file": {
      "file": "data.json",
      "headers": {
        "Content-Type": "application/json"
      }
    }
  }
}
```

and the file like:
```json
{
  "description": "%%dummy-description%%"
}
```

**Comment by DHFW** [comment]
Hi, thank you for the fast turnaround! It works! However... I found an other bug, in the dev-interface. I will make a separate issue for that in that repo (setting an ISO date variable without quotes it does not save (value gets null). Thanks!
