### ISSUE TITLE
Feature Request: Support delay per scenario

### ISSUE THREAD

**Issue by Deklin** [ng-apimock/core#15]
I believe the prior ng-apimock supported delay per scenario, it now seems to be at the top level per this file:
https://github.com/ng-apimock/core/blob/master/src/core/mock/mock.ts

It would be useful to have a default at that level, but be able to override per scenario response.

**Comment by mdasberg** [comment]
@Deklin let me investigate on the change. I will get back to you on that

**Comment by Deklin** [comment]
@mdasberg Thank you and thanks for a fantastic tool!
