### ISSUE TITLE
State returns incorrect state depending on the order of load

### ISSUE THREAD

**Issue by lalmanzar** [ng-apimock/core#17]
I encountered an issue where the wrong mock is being used.

Turns out that if two mock have similar url, and the one with the shortest url is loaded first, the second one never is used.

Example:
```{
	"name": "Countries",
	"request": {
		"url": "/api/v1/countries",
		"method": "GET"
	},
	"responses": {
		"default": {
			"default": true,
			"status": 200,
			"headers": {
				"Content-type": "application/json"
			},
			"data": {}
		}
	}
}
```

and

```
{
	"name": "Provinces Canada",
	"request": {
		"url": "/api/v1/countries/CA",
		"method": "GET"
	},
	"responses": {
		"default": {
			"default": true,
			"status": 200,
			"headers": {
				"Content-type": "application/json"
			},
			"data": {}
		}
	}
}
```

The if you make a request to "/api/v1/countries/CA" the first mock is used since the url also matches.

This could be fixed by sorting the mocks by url length on the state on getMatchingMock. That would make the more complete url to be matched first.

Otherwise the user would need to define all urls ending with "$" so the regex only matches exact urls.

**Comment by mdasberg** [comment]
@lalmanzar we usually use regexes if there are multiple mocks with the same base.
I will investigate if we can look at sorting.
