### ISSUE TITLE
Was watch dropped?

### ISSUE THREAD

**Issue by Local9** [ng-apimock/core#2]
As my project has been using the core since your help, I just wanted to confirm if 'watch' was dropped. No worries if it has, can happily wait if it is going to be added into the core. So far I like the change.

**Comment by mdasberg** [comment]
@Local9 watch mode was not yet implemented. I am working on it now. Hope to release it this week.

**Comment by Local9** [comment]
@mdasberg No worries, loving the change still, has really helped.

**Comment by mdasberg** [comment]
@Local9 I have just release a new version which now adds the watch mode functionality.
