### ISSUE TITLE
Dynamically select a scenario

### ISSUE THREAD

**Issue by FrancescoBorzi** [ng-apimock/core#22]
Is it possible to dynamically select a scenario? That would help a lot when writing automated tests.

For example, a way to send a special HTTP request to the mock server in order to set a specific scenario for a specific route.

It would be great to have such a feature.

**Comment by darlanalves** [comment]
@FrancescoBorzi you are probably looking for this:
https://github.com/ng-apimock/protractor-plugin

**Comment by mdasberg** [comment]
@FrancescoBorzi That is correct. The core has an api which can be called to update scenario's etc. 

Each plugin allows you to change the state of apimock.
For local development you could use https://github.com/ng-apimock/dev-interface and automated testing https://github.com/ng-apimock/protractor-plugin, https://github.com/ng-apimock/webdriverio-plugin or https://github.com/ng-apimock/cypress-plugin

**Comment by FrancescoBorzi** [comment]
thanks all
