### ISSUE TITLE
delayResponse does not seem to work

### ISSUE THREAD

**Issue by farisT** [ng-apimock/core#246]
Hello,

We have been trying to implement a delayResponse on one of the scenarios. We are basically testing that a class does not show before all data is loaded (therefore the delayResponse on the mocked api call).

However the delayResponse does not seem to work within protractor. (The behaviour does work when we set a delay within the GUI of ng-apimock). Is there any way to do this through protractor?

**Comment by Zialus** [comment]
This is not a problem with protractor. It's a problem with the new [schema](https://ngapimock.org/docs/mocks#json-schema).

It forces all responses in the same mock file to share the same delay.

**Comment by mdasberg** [comment]
@farisT do you have an example? Because there are automated tests that verify the using of the delay response.

**Comment by mdasberg** [comment]
@Zialus that is correct. delay is now set for the entire mock. I am thinking of doing an override per scenario though.

**Comment by GrumpyMeow** [comment]
I also just noticed that delayResponse didn't work in my Cypress E2E tests.
Although i think once/twice it did work. So it might be a context thingy...

**Comment by DHFW** [comment]
@mdasberg Having an override delay per scenario would really be appreciated!

**Comment by mdasberg** [comment]
Let me work on that. I should be able to get that working quite fast

**Comment by mdasberg** [comment]
@DHFW @GrumpyMeow this should be resolved now
