### ISSUE TITLE
Show (Error) logging

### ISSUE THREAD

**Issue by ReinderR001** [ng-apimock/core#409]
I have got an issue with the ng-apimock.
When a mockfile contains a reference to a file (to include the body) that does not exist, i don't see error logging.

Is there an option to configure the loglevel (to debug/error)?
Or is it possible to scan all the mockfiles at the start for possible configuration errors?

Thank you in advance!

**Comment by ReinderR001** [comment]
Managed to find a possible solution. Added pull request.

**Comment by mdasberg** [comment]
@ReinderR001 see https://ngapimock.org/docs/debug
