### ISSUE TITLE
Logging Error > ENOENT: no such file or directory

### ISSUE THREAD

**Issue by ReinderR001** [ng-apimock/core#421]
Hello Mischa,

The added debug logging is helpful for troubleshooting.
Thanks a lot!

When a mockfile contains a path to file/directory that not exists the code returns an error in the message.
It would be helpfull when this message also would be added to the debug log.

By adding **exports.log(e.message);** in /middleware/handlers/mock/mock.request.handler.js:43 
i receive the logging like:   
**ng-apimock: handler-request ENOENT: no such file or directory, open 'e2e\mocks\fileNotExists.json'**

**Comment by mdasberg** [comment]
@ReinderR001 can you show me your mock.json file that contains the fileNotExists.json ?

**Comment by ReinderR001** [comment]
@mdasberg I received te message that this issues was closed. That triggert me that i hadn't reply your question. A mock.json for example that contains a filePath. 
`{
  "expression": ".*/categorie$",
  "name": "getCategorie",
  "method": "GET",
  "isArray": true,
  "responses": {
    "standaard": {
      "default": true,
      "status": 200,
      "headers": {
        "Content-Type": "application/json;charset=UTF-8",
        "Access-Control-Allow-Origin": "*"
      },
      "file": "e2e/testdata/categorie.json",
      "statusText": "SUCCESS",
      "delay": 200
    }
  }
}
`
If the file e2e/testdata/categorie.json doesn't exists, the current logging doesn't contain a message that the file isn't found.
The suggestion is to add **exports.log(e.message);** in /middleware/handlers/mock/mock.request.handler.js:43.
Then i receive a errorlog like: ng-apimock: handler-request ENOENT: no such file or directory, open 'e2e/testdata/categorie.json'

**Comment by mdasberg** [comment]
@ReinderR001 I reopened the ticket. Let me see if I can replay it locally

**Comment by mdasberg** [comment]
The file location should be relative so you can just put "file": "categorie.json" in
@ReinderR001 could you verify?

**Comment by ReinderR001** [comment]
Hi Misha, i think we've got a misunderstanding. It isn't a problem to add a file to the mock. That's working fine. 
But in case you make a typo in the mock.json, for example "file": "categorie.json" where the file is named "category.json" it would be helpfull when the error message would tell "no such file or directory, open 'e2e\mocks\categorie.json'.

**Comment by mdasberg** [comment]
ah, yes, now I get it :)
