### ISSUE TITLE
not able to set non-string variables

### ISSUE THREAD

**Issue by ruifang** [ng-apimock/core#6]
Is there a way to set non-string variables? Right now `setVariable()` takes a string for value. I tried passing in a json string of the object, but it comes back with double quotes around them in the mock response. Same thing with numbers.

Thanks.

**Comment by mdasberg** [comment]
@ruifang I will have to check. It should be possible

**Comment by mdasberg** [comment]
@ruifang, The endpoint does support setting an object, only the interpolation of that variable is kind of hard, there is no information available about the type.

```js
{
    "data": {
        "some-key": "%%some-value%%"
    }
}
```

so when I set the variable as boolean true,

this will get interpolated as 

```js
{
    "some-key": "true"
}
```

I will have to get back to you to see if the interpolation can handle this

**Comment by mdasberg** [comment]
@ruifang I updated the interpolation function.

It now handles both strings and objects. So if you set it as a boolean, it will interpolate it as a boolean.

**Comment by mdasberg** [comment]
@ruifang, sorry, still have to merge it.

**Comment by ruifang** [comment]
Thanks! string, number, boolean, and null are working great, but it returns `[object Object]` in the json for the following variable update:
```
curl -X PUT \
  http://localhost:9900/ngapimock/variables \
  -H 'Content-Type: application/json' \
  -H 'X-apimockid: 4' \
  -d '{
	"orderLock": {"locked": true}
}'
```

**Comment by nir-harmonic** [comment]
I am facing the same problem.
As you can see from the comment above, the issue has NOT been solved yet (returns '[object object]' instead of an actual JSON).
Any suggestions?
