### ISSUE TITLE
Duplicate apimockid cookies

### ISSUE THREAD

**Issue by GrumpyMeow** [ng-apimock/core#652]
Hi,

We are using ngapimock in combination with Cypress for our E2E-tests. I’ve created a Cypress command to retrieve the apimockid-cookie from the selectPreset-command and add also the apimockid cookie on the requests triggered by our app. This to allow for running E2E tests in parallel.

In some situations this results in multiple (the same) apimockid cookies to be added to the requests. My strong suspicision is that this leads to a new ngapimock-context.

Is it possible to ensure ngapimock only uses 1
instance of the apimockid cookie? 

Thanks!

**Comment by mdasberg** [comment]
@GrumpyMeow, yes, I have created an demo for Cypress using also cucumber.

[Here](https://github.com/ng-apimock/demo/tree/master/cypress-plugin) we make sure to initialize ng-apimock before each test suite.

**Comment by mdasberg** [comment]
I'll create a pr in the cypress-plugin to detect if a cookie is already present. If it is, we don't set it and use that one, otherwise we set a new cookie.

**Comment by mdasberg** [comment]
@GrumpyMeow should be fixed in version [@ng-apimock/cypress-plugin v2.2.0](https://github.com/ng-apimock/cypress-plugin/releases/tag/v2.2.0)
