### ISSUE TITLE
Ability to mock PATCH requests

### ISSUE THREAD

**Issue by AndreiRazumau** [ng-apimock/core#9]
Hello, 
Do you have an ability to mock PATCH requests ? If so could you please provide examples.

Thanks in advance!

**Comment by mdasberg** [comment]
Hi @AndreiRazumau you can mock any request. If you want to mock a patch request, you can do that by specifying the request method as patch like this:

```json
{
  "name": "my-patch-endpoint",
  "request": {
    "url": "/some/url/to/match",
    "method": "PATCH",
    "body": {
      "something": "^[a-zA-Z]{3,10}$"
    }
  },
  "responses": {
    "ok": {
      "status": 200,
      "default": true
    }
  }
}
```

**Comment by AndreiRazumau** [comment]
@mdasberg Thanks! I will try.
