### ISSUE TITLE
State.matchesBody() has a false positive for similar mocks

### ISSUE THREAD

**Issue by BuruY** [ng-apimock/core#924]
I have created a fix, but am receiving a 403 when trying to push the branch.

Lets say you have two mocks with similar bodies:
Mock A: `body: { nested: { number: '\\d+', identifier: '^[a-zA-Z]{4}$' } }`
and
Mock B: `body: { nested: { number: '\\d+', identifier: '^[a-zA-Z]{4}$', tuple: ['\\d+', '[\'true\'|\'false\']'] } }`

Upon receiving a request with body: `{ nested: { number: 123, identifier: 'abcd', tuple: [1, false] } }`

the `State.matchesBody()` function will return Mock A instead of Mock B.

Fix is ready, how can I contribute?

**Comment by BuruY** [comment]
Done

**Comment by mdasberg** [comment]
@BuruY version [3.5.1](https://github.com/ng-apimock/core/releases/tag/v3.5.1) has just been released with the fix.

Thanks for your help.

**Comment by BuruY** [comment]
Thanks for the quick response!
