### ISSUE TITLE
POST mocks resulting in 404

### ISSUE THREAD

**Issue by Squixx** [ng-apimock/core#957]
Somhow POST mocks result in a 404 when having content-type application/json, while postman calls work.. 

```
{
  "name": "user-userProperties-POST",
  "isArray": true,
  "expression": "api/user/userProperties",
  "request": {
    "url": "/user/userProperties",
    "method": "POST"
  },
  "responses": {
    "default": {
      "default": true,
      "file": "../POST_200.preset.json",
      "headers": { "Content-type": "application/json" }
    },
    "internal-server-error": {
      "status": 500
    }
  }
}
```

post works without content type, but when adding content type the request just times out

**Comment by Squixx** [comment]
nevermind.

Seems content matching matches more explicit after v3.0.0

Be sure to EXACTLY match your body / headers (or ignore them totally)

**Comment by FrancescoBorzi** [comment]
I consider this a regression, see https://github.com/ng-apimock/core/issues/1067
